# Header
menu:
  Home: /
  Archives: /archives
  Videos: /categories/videos
  About me: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-27255613-1
favicon: /favicon.png
twitter: https://twitter.com/alexandreroba
google_plus:
fb_admins:
fb_app_id:
